name: Upload BentoML Dockerized Model with or without Multi-stage Conda Pack

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-bentoml-image:
    if: ${{ github.repository != 'ersilia-os/eos-template' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if we can use this workflow
        run: |
          if [[ -f install.yml ]]; then
            echo "This workflow is not supported for this repository"
            exit 1
          fi
      
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
    
      # log in to dockerhub
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # This might stop working in the future, so we need to keep an eye on it
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Setup conda
        id: setupConda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10.10"

      - name: Install dependencies in Conda environment
        id: installDependenciesInConda
        run: |
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge
          python -m pip install git+https://github.com/ersilia-os/ersilia.git

      - name: Generate the  Dockerfile
        id: generateDockerfile
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          VERSION: ${{ inputs.version}}
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/place_a_dockerfile_in_current_eos_repo.py
          python -m pip install requests
          python place_a_dockerfile_in_current_eos_repo.py $REPO_NAME $VERSION
          rm place_a_dockerfile_in_current_eos_repo.py

      # We cannot tag it as anything other than latest because 
      # ersilia cli only looks for the 'latest' tag
      - name: Build only  AMD64 Image for Testing
        id: buildForTest
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ersiliaos/${{ github.event.repository.name }}:latest
          
      # TODO This is very hacky, maybe we want to use the ersilia test command in the future for this
      - name: Test built image
        id: testBuiltImage
        env:
          PULL_IMAGE: n
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          ersilia -v fetch ${{ github.event.repository.name }} --from_dockerhub
          ersilia -v serve ${{ github.event.repository.name }} --track #Added --track here
          ersilia example -n 1 -f input.csv --predefined
          ersilia -v run -i "input.csv" -o "output.csv"
          ersilia close
          output=$(python .github/scripts/verify_model_outcome.py output.csv)
          if echo "$output" | grep -q "All outcomes are null"; then
            echo "Error in model outcome, aborting build"
            exit 1
          fi
          rm output.csv

      - name: Build and push
        id: buildMultiple
        continue-on-error: true
        uses: docker/build-push-action@v6.7.0
        timeout-minutes: 45
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ersiliaos/${{ github.event.repository.name }}:latest
          
      - name: Set build failure output
        id: buildCheck
        run: |
          if [[ "${{ steps.buildMultiple.outcome }}" == "failure" ]]; then
            echo "::set-output name=failed::true"
            echo "AMD64" > arch.txt 
          else
            echo "::set-output name=failed::false"
            echo "AMD64,ARM64" > arch.txt
          fi
      
      - name: Upload arch.txt
        uses: actions/upload-artifact@v4
        with:
          name: arch
          path: arch.txt
